apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-task
  namespace: cicd
spec:
  workspaces:
    - name: dockerImageArtefact
  params:
    - name: imageName
      type: string
      description: The name of the docker image
      default: alpinehelloworld
  resources:
    inputs:
      - name: docker-source
        type: git
  steps:
    - name: build
      image: docker
      command:
        - sh
        - -c
        - "
          cd $(resources.inputs.docker-source.path) && \
          docker build -t $(params.imageName) . && \
          docker save $(params.imageName) -o $(workspaces.dockerImageArtefact.path)/$(params.imageName).tar
          "
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock

