apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-test-push-pipeline
  namespace: cicd
spec:
  tasks:
    - name: build
      taskRef:
        name: build-task
    - name: test
      taskRef:
        name: test-task
      runAfter:
        - build
    - name: push
      taskRef:
        name: push-task
      runAfter:
        - test
